CREATE DATABASE [WebAppMonitor]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'WebAppMonitor', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DEV\MSSQL\DATA\WebAppMonitor.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'WebAppMonitor_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DEV\MSSQL\DATA\WebAppMonitor_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [WebAppMonitor] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [WebAppMonitor] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [WebAppMonitor] SET ANSI_NULLS OFF
GO
ALTER DATABASE [WebAppMonitor] SET ANSI_PADDING OFF
GO
ALTER DATABASE [WebAppMonitor] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [WebAppMonitor] SET ARITHABORT OFF
GO
ALTER DATABASE [WebAppMonitor] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [WebAppMonitor] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [WebAppMonitor] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [WebAppMonitor] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [WebAppMonitor] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [WebAppMonitor] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [WebAppMonitor] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [WebAppMonitor] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [WebAppMonitor] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [WebAppMonitor] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [WebAppMonitor] SET  DISABLE_BROKER
GO
ALTER DATABASE [WebAppMonitor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [WebAppMonitor] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [WebAppMonitor] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [WebAppMonitor] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [WebAppMonitor] SET  READ_WRITE
GO
ALTER DATABASE [WebAppMonitor] SET RECOVERY FULL
GO
ALTER DATABASE [WebAppMonitor] SET  MULTI_USER
GO
ALTER DATABASE [WebAppMonitor] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [WebAppMonitor] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [WebAppMonitor] SET DELAYED_DURABILITY = DISABLED
GO
USE [WebAppMonitor]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [WebAppMonitor]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [WebAppMonitor] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
